### ISSUE TITLE
Load Promise if missing

### ISSUE THREAD

**Issue by rappen** [davidyack/Xrm.Tools.CRMWebAPI#17]
IE11 does not support promises OoB, so it would be great if it could be loaded by the CRMWebAPI if needed.
Perhaps something like this in the "constructor"?

```
   if (typeof (Promise) === "undefined") {
       LoadPromise();  // Some method loading from promisejs.org
   }
```

**Comment by davidyack** [comment]
Normally handle that by either also associating the poly fill with the form, or in the case of a web resource including the script as follows

<script src="https://www.promisejs.org/polyfills/promise-7.0.4.min.js"></script>

Are you suggesting we should dynamicly load it on the fly?  Any chance you have a reference to another library that is doing that?

**Comment by rappen** [comment]
My thought was that it should be possible to include CRMWebAPI on the form, and that lib would handle any other dependencies it would require.
If other dependencies are introduced in the future, those could also be handled internally so that the "consumer" of the library does not really have to be aware of the internally used technologies.

**Comment by davidyack** [comment]
The library takes a dependency on promises, since that is becoming almost ubiquitous, we will not plan on loading the shim dynamically, you should load it separately if you are supporting environments that do not have it.  One way would be in the build process you could pull and combine any required components and upload as a single web resource if needed - but goal is to keep core library as simple as possible
