### ISSUE TITLE
.Net Core Example Does Not Compile

### ISSUE THREAD

**Issue by glosrob** [davidyack/Xrm.Tools.CRMWebAPI#55]
```
 public static CRMWebAPI GetAPI()
 {
      string authority = "https://login.microsoftonline.com/common";
      string clientId = "<clientid>";
      string crmBaseUrl = "https://xx.crm.dynamics.com";
      var authContext = new AuthenticationContext(authority);
      UserCredential userCreds = new UserCredential("userEmail", "userPassword");
      var result = authContext.AcquireToken(crmBaseUrl, clientId, userCreds);
      CRMWebAPI api = new CRMWebAPI(crmBaseUrl + "/api/data/v8.0/", result.AccessToken);
      return api;
 }
```

I tried this on .Net Core 2 today and 
`UserCredential userCreds = new UserCredential("userEmail", "userPassword");`
No longer has a constructor that accepts a username and password.

**Comment by davidyack** [comment]
Yes, I don't believe .NET Core will be supporting that flow for authentication.  I also believe they have now changed it to UserPasswordCredential instead of UserCredential.  I will leave this open to update the example and also clarify it doesn't work with .NET Core - Thanks

I would look to one of the methods that is more S2S focused such as 
AcquireTokenAsync(string resource, ClientCredential clientCredential)
AcquireTokenAsync(string resource, ClientAssertion clientAssertion)
AcquireTokenAsync(string resource, IClientAssertionCertificate clientCertificate)

**Comment by RafaelCavazza** [comment]
Hi,

Yes, this is a know [issue](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482).

The recommended approach is to create a [Application User ](https://msdn.microsoft.com/en-us/library/mt790170.aspx) and use it's credentials to generate an acess token.
  
      string authority = "https://login.microsoftonline.com/";
      string clientId = "<clientid>";
      string crmBaseUrl = "https://xx.crm.dynamics.com";
      string clientSecret = "<clientSecret>";
      string tenantID = "<tenantId>"; 

      var clientcred = new ClientCredential(clientId, clientSecret);
      var authContext = new AuthenticationContext(authority + tenantID);
      var authenticationResult = await authContext.AcquireTokenAsync(crmBaseUrl, clientcred);
  
      return new CRMWebAPI(crmBaseUrl + "/api/data/v8.0/", authenticationResult.AccessToken);
